package jcbhmr:ressa;

interface ress {

}

interface resast {
  variant program {
    mod(list<program-part>),
    script(list<program-part>),
  }

  variant program-part {
    dir(dir),
    decl(decl),
    stmt(stmt),
  }

  record dir {
    expr: lit,
    dir: string,
  }

  variant lit {
    null,
    string(string-lit),
    number(string),
    bool(bool),
    reg-ex(reg-ex),
    template(template-lit)
  }

  variant string-lit {
    double(string),
    single(string),
  }


}

interface ressa-ffi {
  resource comment-handler {
    handle-comment: func(comment: item);
  }
}

interface ressa {
  resource builder {
    new: static func() -> builder;
  }

  resource default-comment-handler {
    comment-handler-handle-comment: func(a: item);
  }

  resource line {}

  resource parser {}
}

world host {
  import ress;
  import resast;

  import ressa-ffi;
  export ressa;
}
